apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-deployment
  namespace: python-app-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: my-python-app
        image: farandesanjana/mypythonapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: TARGET_HOST
          value: "135.13.21.112"
        - name: TARGET_PORT
          value: "135"
