apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-deployment
  namespace: python-app-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: my-python-app
        image: farandesanjana/mypythonapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-app-ns
spec:
  selector:
    app: python-app
  type: NodePort    # ← changed from ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080   # port on localhost (30000–32767 range)
